kind: DeliveryPipeline
metadata:
  name: my-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
    profiles: []
  - targetId: qsprod
    profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsdev
description: development cluster
gke:
  cluster: projects/gcp-estudo-eng/locations/us-central1-c/clusters/cluster-dev
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsprod
description: production cluster
gke:
  cluster: projects/gcp-estudo-eng/locations/us-central1-c/clusters/cluster-prod
---
